title = "Another Advanture"
baseURL = "https://advanture.amandoabreu.com/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/hjulhytte/"
  youtube = "https://www.youtube.com/channel/UCRglk9sqGxMk9SdT4GEC_TQ"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]